### ISSUE TITLE
Document isnt opening correctly

### ISSUE THREAD

**Issue by LukeAnger1** [LukeAnger1/SWPyMacros#1]
The current test in main testing rotating is unable to open solidworks and only runs correctly if there is a document actively open.

**Comment by LukeAnger1** [comment]
PS C:\Users\<Username>\Desktop\fortCounter\woodAndScrewCounter\testing\SWPyMacros> python3 .\hello_python_world.py
Traceback (most recent call last):
  File "C:\Users\<Username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\win32com\client\dynamic.py", line 84, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\<Username>\Desktop\fortCounter\woodAndScrewCounter\testing\SWPyMacros\hello_python_world.py", line 67, in <module>
    asyncio.run(main())
                ^^^^^^
  File "C:\Users\<Username>\Desktop\fortCounter\woodAndScrewCounter\testing\SWPyMacros\hello_python_world.py", line 17, in main
    sw = win32com.client.Dispatch("SldWorks.Application.{}".format(SWAV))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<Username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\win32com\client\__init__.py", line 118, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch, userName, clsctx)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<Username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\win32com\client\dynamic.py", line 104, in _GetGoodDispatchAndUserName
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<Username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\win32com\client\dynamic.py", line 86, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)
PS C:\Users\<Username>\Desktop\fortCounter\woodAndScrewCounter\testing\SWPyMacros> python3 .\hello_python_world.py
 Solidworks API Version : 31 
 Solidworks Version : 2023
Traceback (most recent call last):
    asyncio.run(test_rotating_CAD())
                ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<Username>\Desktop\fortCounter\woodAndScrewCounter\testing\SWPyMacros\hello_python_world.py", line 78, in test_rotating_CAD
    ck = Model.Extension.SelectByID2("Front", "PLANE", 0, 0, 0, False, 0, ARG_NULL, 0)
         ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'Extension'
PS C:\Users\<Username>\Desktop\fortCounter\woodAndScrewCounter\testing\SWPyMacros> python3 .\hello_python_world.py
 Solidworks API Version : 31 
 Solidworks Version : 2023
C:\Users\<Username>\Desktop\fortCounter\woodAndScrewCounter\testing\SWPyMacros\hello_python_world.py executed in 0.00 seconds until while-loop

**Comment by LukeAnger1** [comment]
This is terminal output. The first run was with solidworks closed. The second was with solidworks open but no CAD open. The third was with a CAD open.

**Comment by LukeAnger1** [comment]
There is also an issue with it crashing with multiple instances open. This is the line that needs fixed
swApp = win32com.client.Dispatch("SldWorks.Application.{}".format(SWAV))
